#ifndef _KEYDEFS_H_
#define _KETDEFS_H_

#define ISE_KEY_RESERVED		0
#define ISE_KEY_ESC			1
#define ISE_KEY_1			2
#define ISE_KEY_2			3
#define ISE_KEY_3			4
#define ISE_KEY_4			5
#define ISE_KEY_5			6
#define ISE_KEY_6			7
#define ISE_KEY_7			8
#define ISE_KEY_8			9
#define ISE_KEY_9			10
#define ISE_KEY_0			11
#define ISE_KEY_MINUS		12
#define ISE_KEY_EQUAL		13
#define ISE_KEY_BACKSPACE		14
#define ISE_KEY_TAB			15
#define ISE_KEY_Q			16
#define ISE_KEY_W			17
#define ISE_KEY_E			18
#define ISE_KEY_R			19
#define ISE_KEY_T			20
#define ISE_KEY_Y			21
#define ISE_KEY_U			22
#define ISE_KEY_I			23
#define ISE_KEY_O			24
#define ISE_KEY_P			25
#define ISE_KEY_LEFTBRACE		26
#define ISE_KEY_RIGHTBRACE		27
#define ISE_KEY_ENTER		28
#define ISE_KEY_LEFTCTRL		29
#define ISE_KEY_A			30
#define ISE_KEY_S			31
#define ISE_KEY_D			32
#define ISE_KEY_F			33
#define ISE_KEY_G			34
#define ISE_KEY_H			35
#define ISE_KEY_J			36
#define ISE_KEY_K			37
#define ISE_KEY_L			38
#define ISE_KEY_SEMICOLON		39
#define ISE_KEY_APOSTROPHE		40
#define ISE_KEY_GRAVE		41
#define ISE_KEY_LEFTSHIFT		42
#define ISE_KEY_BACKSLASH		43
#define ISE_KEY_Z			44
#define ISE_KEY_X			45
#define ISE_KEY_C			46
#define ISE_KEY_V			47
#define ISE_KEY_B			48
#define ISE_KEY_N			49
#define ISE_KEY_M			50
#define ISE_KEY_COMMA		51
#define ISE_KEY_DOT			52
#define ISE_KEY_SLASH		53
#define ISE_KEY_RIGHTSHIFT		54
#define ISE_KEY_KPASTERISK		55
#define ISE_KEY_LEFTALT		56
#define ISE_KEY_SPACE		57
#define ISE_KEY_CAPSLOCK		58
#define ISE_KEY_F1			59
#define ISE_KEY_F2			60
#define ISE_KEY_F3			61
#define ISE_KEY_F4			62
#define ISE_KEY_F5			63
#define ISE_KEY_F6			64
#define ISE_KEY_F7			65
#define ISE_KEY_F8			66
#define ISE_KEY_F9			67
#define ISE_KEY_F10			68
#define ISE_KEY_NUMLOCK		69
#define ISE_KEY_SCROLLLOCK		70
#define ISE_KEY_KP7			71
#define ISE_KEY_KP8			72
#define ISE_KEY_KP9			73
#define ISE_KEY_KPMINUS		74
#define ISE_KEY_KP4			75
#define ISE_KEY_KP5			76
#define ISE_KEY_KP6			77
#define ISE_KEY_KPPLUS		78
#define ISE_KEY_KP1			79
#define ISE_KEY_KP2			80
#define ISE_KEY_KP3			81
#define ISE_KEY_KP0			82
#define ISE_KEY_KPDOT		83

#define ISE_KEY_ZENKAKUHANKAKU	85
#define ISE_KEY_102ND		86
#define ISE_KEY_F11			87
#define ISE_KEY_F12			88
#define ISE_KEY_RO			89
#define ISE_KEY_KATAKANA		90
#define ISE_KEY_HIRAGANA		91
#define ISE_KEY_HENKAN		92
#define ISE_KEY_KATAKANAHIRAGANA	93
#define ISE_KEY_MUHENKAN		94
#define ISE_KEY_KPJPCOMMA		95
#define ISE_KEY_KPENTER		96
#define ISE_KEY_RIGHTCTRL		97
#define ISE_KEY_KPSLASH		98
#define ISE_KEY_SYSRQ		99
#define ISE_KEY_RIGHTALT		100
#define ISE_KEY_LINEFEED		101
#define ISE_KEY_HOME		102
#define ISE_KEY_UP			103
#define ISE_KEY_PAGEUP		104
#define ISE_KEY_LEFT		105
#define ISE_KEY_RIGHT		106
#define ISE_KEY_END			107
#define ISE_KEY_DOWN		108
#define ISE_KEY_PAGEDOWN		109
#define ISE_KEY_INSERT		110
#define ISE_KEY_DELETE		111
#define ISE_KEY_MACRO		112
#define ISE_KEY_MUTE		113
#define ISE_KEY_VOLUMEDOWN		114
#define ISE_KEY_VOLUMEUP		115
#define ISE_KEY_POWER		116	/* SC System Power Down */
#define ISE_KEY_KPEQUAL		117
#define ISE_KEY_KPPLUSMINUS		118
#define ISE_KEY_PAUSE		119

#define ISE_KEY_KPCOMMA		121
#define ISE_KEY_HANGEUL		122
#define ISE_KEY_HANGUEL		KEY_HANGEUL
#define ISE_KEY_HANJA		123
#define ISE_KEY_YEN			124
#define ISE_KEY_LEFTMETA		125
#define ISE_KEY_RIGHTMETA		126
#define ISE_KEY_COMPOSE		127

#define ISE_KEY_EXCLAM		129
#define ISE_KEY_AT			130
#define ISE_KEY_SHARP		131
#define ISE_KEY_DOLLAR		132
#define ISE_KEY_PERCENT		133
#define ISE_KEY_CARET		134
#define ISE_KEY_AMPERSAND	135
#define ISE_KEY_ASTERISK	136
#define ISE_KEY_LPAREN		137
#define ISE_KEY_RPAREN		138

#define ISE_KEY_MODECHANGE	247
#define ISE_KEY_SETTING		248

#define ISE_KEY_MAX			255

#endif
